# ---------- 1-й этап: сборка ----------
FROM maven:3.9.7-eclipse-temurin-21 AS builder
WORKDIR /workspace

# ---------- 1-й этап: сборка ----------
FROM maven:3.9.7-eclipse-temurin-21 AS builder
WORKDIR /workspace

# копируем ВСЁ, что нужно для payment-service
COPY . .

RUN mvn -pl payment-service -am clean package -DskipTests


# Теперь остальные исходники
COPY . .

RUN mvn -pl payment-service -am clean package -DskipTests

# ---------- 2-й этап: рантайм ----------
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /workspace/payment-service/target/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]
