# ---------- 1-й этап: сборка ----------
FROM maven:3.9.7-eclipse-temurin-21 AS builder
WORKDIR /workspace

# Сначала только POM-ы — чтобы кэшировались зависимости
COPY pom.xml .
COPY payment-service/pom.xml payment-service/pom.xml
RUN mvn -B -q dependency:go-offline

# Теперь остальные исходники
COPY . .

RUN mvn -pl payment-service -am clean package -DskipTests

# ---------- 2-й этап: рантайм ----------
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /workspace/payment-service/target/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]
