version: "3.8"

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile-payment
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8080

  store-service:
    build:
      context: .
      dockerfile: Dockerfile-store
    container_name: store-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8081
      - REDIS_HOST=redis
      - PAYMENT_SERVICE_URL=http://payment-service:8080
    depends_on:
      - redis
      - payment-service

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    ports:
      - "8089:8080"
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-store-realm.json:/opt/keycloak/data/import/store-realm.json
volumes:
  keycloak_data:
